function []=Plot_FRF_Analytical(Mode,FreqResEq,FRF_freq)
% ----- Õº¥∞ Ù–‘…Ë÷√ -----------------------------------------------
fig=gcf;
NameArrayGcf={'Name','color','position','Units'};
VlaueArrayGcf={'Frequency Response Function','white',[500,300,1500,500],'centimeters'};
set(fig,NameArrayGcf,VlaueArrayGcf);
% ----- ªÊÕº -----------------------------------------------------
subplot(2,3,1)
plot(FRF_freq,log10(abs(FreqResEq.rad.amp))*20,'LineWidth',1.5)
title('Radial Frequency Response Function')
xlabel('\it f \rm(Hz)')
ylabel('\it Mag \rm(m/N)')
set(gca,'FontSize',11,'FontName','Times New Roman','xlim',[0 max(FRF_freq)])
legend({'v=0','v=2','v=4','v=6'},'Location','best','NumColumns',4)
subplot(2,3,4)
plot(FRF_freq,FreqResEq.rad.pha,'LineWidth',1.5)
xlabel('\it f \rm(Hz)')
ylabel('\it \phi \rm(\circ)')
set(gca,'FontSize',11,'FontName','Times New Roman','xlim',[0 max(FRF_freq)])
subplot(2,3,2)
plot(FRF_freq,log10(abs(FreqResEq.tan.amp))*20,'LineWidth',1.5)
title('Tangential Frequency Response Function')
xlabel('\it f \rm(Hz)')
ylabel('\it Mag \rm(m/N)')
set(gca,'FontSize',11,'FontName','Times New Roman','xlim',[0 max(FRF_freq)])
legend({'v=0','v=2','v=4','v=6'},'Location','best','NumColumns',4)
subplot(2,3,5)
plot(FRF_freq,FreqResEq.tan.pha,'LineWidth',1.5)
xlabel('\it f \rm(Hz)')
ylabel('\it \phi \rm(\circ)')
set(gca,'FontSize',11,'FontName','Times New Roman','xlim',[0 max(FRF_freq)])
subplot(2,3,3)
plot(FRF_freq,log10(abs(FreqResEq.tq.amp))*20,'LineWidth',1.5)
title('Torque Frequency Response Function')
xlabel('\it f \rm(Hz)')
ylabel('\it Mag \rm(m/N)')
set(gca,'FontSize',11,'FontName','Times New Roman','xlim',[0 max(FRF_freq)])
legend({'v=0','v=2','v=4','v=6'},'Location','best','NumColumns',4)
subplot(2,3,6)
plot(FRF_freq,FreqResEq.tq.pha,'LineWidth',1.5)
xlabel('\it f \rm(Hz)')
ylabel('\it \phi \rm(\circ)')
set(gca,'FontSize',11,'FontName','Times New Roman','xlim',[0 max(FRF_freq)])
end
